### ISSUE TITLE
Ability to disable usage of intl 

### ISSUE THREAD

**Issue by Sensetivity** [yiisoft/i18n#14]
Hello. I wonder if we can have ability to disable usage PHP intl-extention and use fallbackFormat() function in places when we can.

For example on shared hosting developers haven`t access to installation of extention or update it to proper version. Its mean that we will have a message like a "Total {count, number} {count, plural, one{item} other{items}}." and no ability to fix it. But this will be work fine on fallback functions.

**Comment by samdark** [comment]
Done via simple formatter.
