### ISSUE TITLE
Add region to Locale::language() or some method returns language-region

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/i18n#35]
Good day. In my case i set `Application::charset` as **ru-RU**. It works for any `IntlMessageFormatter` without currency pattern. For example
```
<?php

$value = '1419326100';
echo $formatter->format('{0, number, integer}', [$value], $locale->language());  //1 419 326 100
echo $formatter->format('{0, number, currency}', [$value], $locale->language());  //1 419 326 100,00 XXXX
echo $formatter->format('{0, number, currency}', [$value], $locale->language() . '-' . $locale->region());  //1 419 326 100,00 ₽
```

So - can you append region (if it set) to language or some short method who return locale as `language-region` format. Thanks

**Comment by samdark** [comment]
IntlMessageFormatter works well with `$locale->asString()`. Do you want to trim everything except language and region?

**Comment by Gerych1984** [comment]
> IntlMessageFormatter works well with `$locale->asString()`. Do you want to trim everything except language and region?

Hm, sorry my mistake - i forgot about this method. And with this it work well
