### ISSUE TITLE
Ability to disable intl in yii\i18n\Formatter (eg for dates)

### ISSUE THREAD

**Issue by ptz-nerf** [yiisoft/i18n#5]
It would be nice if it will be possible to force disable the intl in Formatter.
There is a problem when ICU is intalled on server, but timezones data is outdated. So, all operations with dates via Formatter are incorrect.
Yes, I can extend Formatter, but I cann't override private formatDateTimeValue. Overriding all date functions seems strange.
Related #9540

**Comment by samdark** [comment]
No longer applies to the code in this repository.
