### ISSUE TITLE
formatter pattern

### ISSUE THREAD

**Issue by dkhlystov** [yiisoft/i18n#6]
It would be nice to get the formatting pattern according to locale for date (may be time too)
`Yii::$app->formatter->getDatePattern()` would return `'dd.MM.yy'` for `Yii::$app->language = 'ru-RU'`

[implementation here](http://stackoverflow.com/questions/8827514/get-date-format-according-to-the-locale-in-php)

**Comment by samdark** [comment]
No longer applies to the code in this repository.
