### ISSUE TITLE
Add Date range formatter

### ISSUE THREAD

**Issue by cebe** [yiisoft/i18n#8]
format date ranges like `1.-5. January 2016`, `Oct 4-6, 2016`.

``` php
asDateRange($fromDate, $toDate)
```

similar implementation in ruby: https://github.com/darkleaf/date_range_formatter

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/10820

**Comment by samdark** [comment]
No longer applies to the code in this repository.
