### ISSUE TITLE
Ability to set showing intervals in asDuration() formatter

### ISSUE THREAD

**Issue by kirillarutyunov** [yiisoft/i18n#9]
### What steps will reproduce the problem?

`<?= Yii::$app->formatter->asDuration($customTime) ?>`
### What is the expected result?

`25 days, 5 hours, 39 minutes, 43 seconds`
### What i want to get?

`25 days, 5 hours`

It will be good to make ability to set intervals wich will be showing in the result: years, months days, hours, minutes, seconds. For example:

`<?= Yii::$app->formatter->asDuration($customTime, ['seconds' => false, 'minutes' => false]) ?>`
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.7+ |
| PHP version | any |
| Operating system | any |

**Comment by tomaszkane** [comment]
Other solution is:
`<?= Yii::$app->formatter->asDuration($customTime, ['roundTo' => 'minutes']) ?>`
Just choose what precision do you need.

**Comment by samdark** [comment]
No longer applies to the code in this repository.
